#----------------------------------------------------------------------
# This file was generated by D:\Python27\Lib\site-packages\wx-3.0-msw\wx\tools\img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

AppIcon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAA+pJ"
    "REFUWIXVl09sVFUUxr/vvkenU2iH+SctNMZFownBIEQ3RiutrTRoiDHYGBN3hkhMQIMa3Uhw"
    "gcTG6EY0VtFIw6J2YWpSQ2AYCAordiZGMBqxoDPzZoZCben0vfu5INZKWzvz5I9+y/vuOed3"
    "zrv3nnuJKtUyfL5hammkh1AvgNUC6wGAkA/gZxBfutP+UG5jS75an1ftq1A8W1xDq1cJrQCQ"
    "IXUKBhcYyAZykjRaJ7GHUNQa8255Q+IQSF0XgFQm3y7yTQiHHQXv57uac/PNS2dzywLrPAli"
    "G4QPSg+n9v9rgMQRbzWpD60xn5aPJfZjN+1iDpNHCh0w2CtxgJQFsApCBcRZJwhO5bubf5w9"
    "31RDeSO1cAUGVZdMef0QRovF1OvoZVCt03im2Gtgt4P4HsAFgRFCbQCaBR6qsO698Y4mb16A"
    "dDa3rIK6lGPtfYTdLvGpUlfqfE1p7ZKJP1BuLHfFL/25GNtGzkSKS5LrjWNfgmARYEfxkfSF"
    "GYB0NtdsrXlG5AYAUQDLCA0VO9Nv1RR8EcVOXIy7lel3RFYi41MvEADix0p3myDoE1mU5YB1"
    "zHdOEExHJqbKv25eNXE9AQAgkfVaIRw0tPuYyHqttOoXeaqhfqJv9P7bJ693wPmUPFrYKbDT"
    "0GqbyHKY4K0nz0UTI15TGACR3wBoMwI3GdqDYTL//crSzazXy2EADG0RgHPLzwEDolGWZ0MZ"
    "yyYArAxj6/tuFIJ1AcDCuGGcQBCAqprOtXIYrAGQM4SKBnZtKICQahk+3wDgCRBfGAifC3w6"
    "li0vvynRd8lMNUS2Cqx3p/0DpmLrPiE06cp/40ZDxA+XYsl2byepLbTandvYkncvd8eKsePl"
    "V1zf73MUHEhmCoMST7vyryzkyETs5d/aVxZmjyW/LjQ6k0H62rlyaXy5K2i1DrQ9IgMD7fC6"
    "06cBwAWAsYfiP8Wy5WcN7BZKjxPa6tNdsPvR1wiAv/UIVtTuG3fumSDQyFZg8AupgcB3v/K6"
    "E2MzySxcsJujme031hG/COCjtpEzB0rRRNpa4yxkFATO+LVjpI5bmW/njAdQ4PLS2IblY/Pd"
    "E+fs/x823TkFYLSWLACg0LFiHMAcsMV0y3/B/wsgMeI1pY7mH209eS4656PEZKbQGcuW77hh"
    "AEuc6XqBz09caXgRg3Jg/uoDyYz3GIA9ru/POQv+SVW9jGYrncmttTT7JH5MaonA9cbaAWvM"
    "2xD7Sp2JoWpfRcB/YA3UXAEASB3JPyjDvQIvAmikZEh85nWk+mvJHghZAa/rthOE9gC4B8K9"
    "IIY9pvbXGhwIWQEAV1f9Ue85AHdFo5Ovhb1N/wEVzKdWo6hQQgAAAABJRU5ErkJggg==")

